#!/bin/sh
HISTFILE="$ZDOTDIR"/.history
HISTSIZE=1000
SAVEHIST=1000
# eval "$(fnm env)"
export PATH=$HOME/.local/bin:/usr/local/bin:/opt/opengrads:/opt/nvim/usr/bin:/opt/cdo/bin:/opt/Museeks/:/opt/love2d/bin:$PATH

# nvm sourcing
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# for WRF
export DIR="/home/aditya/Downloads/Build_WRF/LIBRARIES"
export CC="gcc"
export CXX="g++"
export FC="gfortran"
export FCFLAGS="-m64 -fallow-argument-mismatch"
export F77="gfortran"
export FFLAGS="-m64 -fallow-argument-mismatch"
export LDFLAGS="-L/usr/lib"
export CPPFLAGS="-I/usr/include"
export WRFIO_NCD_LARGE_FILE_SUPPORT=1
export WRF_DIR="/home/aditya/Downloads/Build_WRF/WRF-4.3"
export JASPERLIB="$DIR/grib2/lib"
export JASPERINC="$DIR/grib2/include"
# export PATH="$DIR/netcdf/bin:$PATH"
export NETCDF="/usr"
export NETCDF_classic=1
