#!/bin/sh
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
# alias cp="cp -i"
# alias mv='mv -i'
# alias rm='rm -i'

# easier to read disk
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# systemd
alias list_systemctl="systemctl list-unit-files --state=enabled"


alias v='nvim'
alias zshconfig="nvim ~/.config/zsh/"
alias d="dirs -v"
#alias config='/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME' # bare git repository
alias rfm='ranger'

# Changing "ls" to "exa"
alias ls='exa --group-directories-first' # my preferred listing
alias la='exa -a --group-directories-first'  # all files and dirs
alias ll='exa -l --group-directories-first'  # long format
alias lal='exa -al --group-directories-first' # long format with all files and dirs
alias lt='exa -aT --group-directories-first' # tree listing

#ufetch
#ufetch-linux
#neofetch
#neofetch --ascii_distro macos

alias luamake=/home/aditya/.config/nvim/lua-ls/lua-language-server/3rd/luamake/luamake
